begin;

create table public.user_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_mac text not null,
  zone text,
  created_at timestamptz not null default now(),
  constraint user_devices_user_mac_key unique (user_id, device_mac),
  constraint user_devices_mac_format check (
    device_mac ~* '^(?:[0-9A-F]{2}:){5}[0-9A-F]{2}$'
  )
);

create index user_devices_user_id_idx
  on public.user_devices (user_id);

create table public.sensor_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_mac text,
  zone text,
  temperature numeric(5,2),
  humidity numeric(5,2),
  soil_moisture numeric(5,2),
  soil_ph numeric(4,2),
  pump_status boolean not null default false,
  created_at timestamptz not null default now(),
  constraint sensor_data_humidity_range check (
    humidity is null or humidity between 0 and 100
  ),
  constraint sensor_data_soil_moisture_range check (
    soil_moisture is null or soil_moisture between 0 and 100
  ),
  constraint sensor_data_soil_ph_range check (
    soil_ph is null or soil_ph between 0 and 14
  ),
  constraint sensor_data_mac_format check (
    device_mac is null or device_mac ~* '^(?:[0-9A-F]{2}:){5}[0-9A-F]{2}$'
  )
);

create index sensor_data_user_created_at_idx
  on public.sensor_data (user_id, created_at desc);

alter table public.user_devices enable row level security;
alter table public.sensor_data enable row level security;
alter table public.sensor_data replica identity full;

revoke all on table public.user_devices from anon;
revoke all on table public.sensor_data from anon;
revoke all on sequence public.user_devices_id_seq from anon;
revoke all on sequence public.sensor_data_id_seq from anon;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.user_devices to authenticated;
grant select, insert, update on table public.sensor_data to authenticated;
grant usage, select on sequence public.user_devices_id_seq to authenticated;
grant usage, select on sequence public.sensor_data_id_seq to authenticated;

create policy "users_select_own_devices"
  on public.user_devices
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "users_insert_own_devices"
  on public.user_devices
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "users_update_own_devices"
  on public.user_devices
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "users_delete_own_devices"
  on public.user_devices
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "users_select_own_sensor_data"
  on public.sensor_data
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "users_insert_own_sensor_data"
  on public.sensor_data
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "users_update_own_sensor_data"
  on public.sensor_data
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sensor_data'
  ) then
    alter publication supabase_realtime add table public.sensor_data;
  end if;
end
$$;

commit;
